//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCategories
    {
        public int Id { get; set; }
        public int IdPost { get; set; }
        public int IdCategory { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
