//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Posts
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int IdWriter { get; set; }
        public string Body { get; set; }
        public System.DateTime EffectDate { get; set; }
        public Nullable<System.DateTime> NullDate { get; set; }
        public int IdCategory { get; set; }
        public bool IsDraft { get; set; }
        public string Summary { get; set; }
        public string PrincipalImageName { get; set; }
        public bool DeletedByComplaintsOrVotes { get; set; }
        public string WriterUserName { get; set; }
    }
}
