USE [DotW]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[vw_Comments] WITH SCHEMABINDING AS
SELECT C.[Id]
	  ,C.[IdPost]
	  ,C.[Commentary]
	  ,C.[IdUser]
	  ,U.Name AS WriterUserName
FROM dbo.Comments C
INNER JOIN dbo.Posts P ON P.Id = C.IdPost
INNER JOIN dbo.Users U ON C.IdUser = U.Id
WHERE C.[NullDate] IS NULL AND P.[NullDate] IS NULL AND P.[IsDraft] = 0
GO

SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO

CREATE UNIQUE CLUSTERED INDEX [uci_CommentId] ON [dbo].[vw_Comments]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE FULLTEXT INDEX ON [dbo].[vw_Comments](
[Commentary] LANGUAGE 'Spanish')
KEY INDEX [uci_CommentId]ON ([CommentsCatalog], FILEGROUP [PRIMARY])
WITH (CHANGE_TRACKING = AUTO, STOPLIST = SYSTEM)

GO


